### PR TITLE
next meetup section with map and presentation placeholders

### PR DESCRIPTION
**Pull request by matldupont**

### CODE REVIEW

**Comment by matldupont** [comment]
Heads up, I couldn't get pretty-quick working properly so I had to commit without verification.   

Ever come across: 'Error: fatal: Not a valid object name master' ?

**Comment by ericadamski** [comment]
I'll take a look @matldupont

**Comment by ericadamski** [comment]
So it seems you'll have to checkout master before you can run pretty-quick. Bizarre 🤔

I am going to make it mobile responsive and maybe for talks just put `Coming Soon` or something?

What do you think @matldupont ?

**Comment by ericadamski** [comment]
screenshot-2018-6-13 ottawa react
screenshot-2018-6-13 ottawa react 1


What do you think?

**Comment by matldupont** [comment]
Sounds good to me!  I still have some work to do on those cards, but should have some time later today before the JS meetup.  I think "Coming Soon" works for now, or even the three cards showing "TBD".  I'm good with either.

Having the map and next meetup areas side by side on a very wide screen is cool, but I think it would have to collapse pretty quick so I like it stacked too.  The map being second when stacked vertically is nice.

I might enlarge the cards as well when that area is full width, but I'll play around.

**Comment by ericadamski** [comment]
I will push my code then and you can play around :)

**Comment by matldupont** [comment]
@ericadamski Still needs some responsive adjustments, but the FlipCards are looking pretty cool.  Check it out

**Review by ericadamski — APPROVED** [review]

**Pull request merged**
